import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "BestAIFinds terms of service and conditions of use.",
};

export default function TermsPage() {
  return (
    <article className="mx-auto max-w-3xl px-4 py-16 prose prose-gray dark:prose-invert">
      <h1>Terms of Service</h1>
      <p className="lead">Last updated: May 2026</p>

      <h2>1. Acceptance of Terms</h2>
      <p>By accessing and using BestAIFinds (bestaifinds.com), you agree to be bound by these Terms of Service. If you do not agree, please do not use our services.</p>

      <h2>2. Description of Service</h2>
      <p>BestAIFinds provides free and premium online tools for file conversion, image editing, AI writing, video processing, and more. Some tools process data in your browser; others require server-side processing.</p>

      <h2>3. User Responsibilities</h2>
      <ul>
        <li>You must not upload illegal, harmful, or copyrighted content without authorization</li>
        <li>You must not attempt to abuse, overload, or exploit our services</li>
        <li>You are responsible for any content you process using our tools</li>
        <li>You must not use automated scripts to access our services without permission</li>
      </ul>

      <h2>4. Intellectual Property</h2>
      <p>All content, design, and code on BestAIFinds is our intellectual property. You retain ownership of files you upload and process. We do not claim ownership over your processed files.</p>

      <h2>5. AI-Generated Content</h2>
      <p>Content generated by our AI writing tools is provided as-is. You are responsible for reviewing and verifying AI-generated content before use. We do not guarantee the accuracy, originality, or appropriateness of AI outputs.</p>

      <h2>6. File Handling</h2>
      <ul>
        <li>Browser-processed files never leave your device</li>
        <li>Server-processed files are automatically deleted within 1 hour</li>
        <li>We do not access, review, or share your uploaded files</li>
        <li>Maximum file size: 50MB (free) / 200MB (Pro)</li>
      </ul>

      <h2>7. Subscriptions and Payments</h2>
      <ul>
        <li>Pro subscriptions are billed monthly or annually</li>
        <li>You may cancel at any time; access continues until the billing period ends</li>
        <li>Refunds are available within 7 days of purchase if you have not used premium features</li>
      </ul>

      <h2>8. Limitation of Liability</h2>
      <p>BestAIFinds is provided &quot;as is&quot; without warranties of any kind. We are not liable for data loss, file corruption, or any damages resulting from use of our services. Always keep backups of your original files.</p>

      <h2>9. Changes to Terms</h2>
      <p>We may update these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.</p>

      <h2>10. Contact</h2>
      <p>For questions about these terms, contact: <a href="mailto:legal@bestaifinds.com">legal@bestaifinds.com</a></p>
    </article>
  );
}
